#!/bin/bash
# Check code style before commit.

# Need to check whether the installation package
install_pkgs=(scss-lint)

for pkg_name in ${install_pkgs[@]}
do
    which ${pkg_name} &> /dev/null
    if [ $? -ne 0 ]; then
        echo ""
        echo -e "\033[1;41mERROR\033[0m: ${pkg_name} not found"
        if [ $pkg_name == 'scss-lint' ]; then
            echo "INSTALL WITH: sudo gem install scss-lint"
        else
            echo "INSTALL WITH: sudo npm install -g ${pkg_name}"
        fi
        exit 1
    fi
done

# Configuration need to check the file
staged="git diff --cached --name-only --diff-filter=ACMR --"
unstaged="git diff --name-only --diff-filter=ACMR --"
js_files="*.js"
jsx_files="*.jsx"
scss_files="*.scss"

# Kit json or yml configuration file
root=$(git rev-parse --show-toplevel)
eslint_conf="${root}/src/.eslintrc"
scsslint_conf="${root}/src/scsslint.yml"

# Check code default prompt information
function echoPrompt() {
    if $1; then
        echo -e "\033[1;32mOk! >>\033[0m check through the $2 code style."
    else
        echo -e "\n\033[1;41mCOMMIT FAILED\033[0m:\n\
Some $2 files are invalid. Please fix errors and try committing again."
        exit 1
    fi
}

# To determine whether these modified files is added
function isAdded() {
    if [ "$1" != "" ]; then
        for file in $1; do
            if [[ $2 =~ ${file} ]]; then
                echo -e "Changes not staged for commit:\n\
(use 'git add <file>...' to update what will be committed)\n\
\033[31m${file}\033[0m"
                exit 1
            fi
        done
    fi
}

##### JS code check #####
# ESLint
js_pass=true
staged_js_files=$(${staged} ${js_files})
unstaged_js_files=$(${unstaged} ${js_files})

if [ "$staged_js_files" != "" ]; then
    isAdded "$unstaged_js_files" "$staged_js_files"
    echo -e "\n\033[1;34mjs code check\033[0m:\n$staged_js_files"
    for file in ${staged_js_files}; do
        ./src/node_modules/.bin/eslint ${file}
        if [[ $? -ne 0 ]]; then
            js_pass=false
        fi
    done
    echoPrompt $js_pass "js"
fi

##### JSX code check #####
# ESLint
jsx_pass=true
staged_jsx_files=$(${staged} ${jsx_files})
unstaged_jsx_files=$(${unstaged} ${jsx_files})

if [ "$staged_jsx_files" != "" ]; then
    isAdded "$unstaged_jsx_files" "$staged_jsx_files"
    echo -e "\n\033[1;34mjsx code check\033[0m:\n$staged_jsx_files"
    for file in ${staged_jsx_files}; do
        ./src/node_modules/.bin/eslint ${file}
        if [[ $? -ne 0 ]]; then
            jsx_pass=false
        fi
    done
    echoPrompt $jsx_pass "jsx"
fi

##### Scss code check #####
# ScssLint
scss_pass=true
staged_scss_files=$(${staged} ${scss_files})
unstaged_scss_files=$(${unstaged} ${scss_files})

if [ "$staged_scss_files" != "" ]; then
    isAdded "$unstaged_scss_files" "$staged_scss_files"
    echo -e "\n\033[1;34mscss code check\033[0m:\n$staged_scss_files"
    for file in ${staged_scss_files}; do
        scss-lint -c ${scsslint_conf} ${file}
        if [[ $? -ne 0 ]]; then
            scss_pass=false
        fi
    done
    echoPrompt $scss_pass "scss"
fi

if [ $js_pass -a $jsx_pass -a $scss_pass ]; then
    exit 0
fi
